### ISSUE TITLE
Kamus-encryptor crashes when attempting to inject a Linkerd 2 sidecar

### ISSUE THREAD

**Issue by ncthbrt** [Soluto/helm-charts#33]
Searching through the chart, I noticed that "automountServiceAccountToken: false" is specified in the encryptor. The service account token is required for correct meshing in Linkerd.

**Comment by omerlh** [comment]
Thanks for filing this issue! As the service account token is not used in the encryptor, we assumed it's more secure not to mount it. Can you please open a PR and add an option to the chart to allow mounting it? Basically, change the `automountServiceAccountToken`?

**Comment by ncthbrt** [comment]
Thanks. I'll do so.
