### ISSUE TITLE
Add support for UseKeyDerivation

### ISSUE THREAD

**Issue by dmbeck-e2x** [Soluto/helm-charts#39]
0.6.3 of Kamus allowed the key to be derived from the service account when using AESKey as the provider, but this was not added to the helm chart.

Add `keyManagement.AES.useKeyDerivation` to the helm chart.

**Comment by omerlh** [comment]
Yes, sure - sorry for not adding it - can you please file a PR?

**Comment by dmbeck-e2x** [comment]
Created pull request: #41

**Comment by shaikatz** [comment]
Done
