### ISSUE TITLE
Update kubectl port-forward directions

### ISSUE THREAD

**Issue by Yitaek** [Soluto/helm-charts#5]
Currently when you install with default settings (i.e. ClusterIP), Helm helper/notes prints out the following:

```
export POD_NAME=$(kubectl get pods --namespace default -l "app=kamus,release=kamus" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080
```

POD_NAME defaults to the decryptor component, so to actually use the encryptor component, we can change the POD_NAME to the following instead to specify it:

```
export POD_NAME=$(kubectl get pods --namespace default -l "app=kamus,release=kamus,component=encryptor" -o jsonpath="{.items[0].metadata.name}")
```

Also, it seems that {{ .Values.service.internalPort }} does not exist and is instead hardcoded to port 9999, so the kubectl port-forward command should also be updated to 

```kubectl port-forward $POD_NAME 8080:9999```

**Comment by omerlh** [comment]
Thanks for pointing it out! Your fix makes sense to me, do you want to open a PR?

**Comment by Yitaek** [comment]
Yup, just submitted a PR (wasn't sure if you had a preferred method for collaboration so just forked for now). Thanks for open sourcing this tool!

**Comment by omerlh** [comment]
Thank you! If you use it please share the experience with us, we would like to hear - and I will be happy adding a logo on our readme of the users :)
