### ISSUE TITLE
Bug - helm package publish date is incorrect

### ISSUE THREAD

**Issue by omerlh** [Soluto/helm-charts#9]
When looking on the [hub UI](https://hub.helm.sh/charts/soluto/kamus), you can see that all packages have the same publish date:
![image](https://user-images.githubusercontent.com/6730584/52365195-a0cbbb00-2a4f-11e9-9ab1-0ec26497e10d.png)
This is due to a bug of how we use `helm merge` - see this issue (helm/helm#4482). Fix should require some work to fix how we publish charts. An alternative is to use chartmuseum binary - see this [slack thread](https://kubernetes.slack.com/archives/C6E3XH1ED/p1549475530218100).

**Comment by MatthiasLohr** [comment]
I never worked with `helm merge`, don't even know what is does. But I'm running into the same problem just using `helm repo index`.

**Comment by shaikatz** [comment]
Fixed by #47
